import * as z from "zod"
import { CompleteUser, RelatedUserModel } from "./index"

export const NoteModel = z.object({
  /**
   * Unique note id
   * @default generated by prisma and cuid()
   */
  id: z.string(),
  /**
   * The note's title
   */
  title: z.string(),
  /**
   * The note's body text
   */
  body: z.string(),
  createdAt: z.date(),
  updatedAt: z.date(),
  /**
   * id of associated user entry (foreign key)
   */
  userId: z.string(),
})

export interface CompleteNote extends z.infer<typeof NoteModel> {
  user: CompleteUser
}

/**
 * RelatedNoteModel contains all relations on your model in addition to the scalars
 *
 * NOTE: Lazy required in case of potential circular dependencies within schema
 */
export const RelatedNoteModel: z.ZodSchema<CompleteNote> = z.lazy(() => NoteModel.extend({
  /**
   * Associated User entry
   */
  user: RelatedUserModel,
}))
